#! /bin/sh

chosen=$(printf "Shutdown\nRestart\nLock\nLogout" | rofi -dmenu -i -theme-str '@import "config.rasi"')

case "$chosen" in
"Shutdown") poweroff ;;
"Restart") reboot ;;
"Lock") i3lock -i ~/Downloads/i3-wallpaper-blurred.png ;;
"Logout") i3-msg exit ;;
*) exit 1 ;;
esac
