#! /bin/sh

chosen=$(printf "Shutdown\nRestart\nSleep\nLock" | rofi -dmenu -i -theme-str '@import "config.rasi"')

case "$chosen" in
"Shutdown") poweroff ;;
"Restart") reboot ;;
"Sleep") systemctl suspend ;;
"Lock") betterlockscreen -l ;;
*) exit 1 ;;
esac
